[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/portfolio/*"
  to = "/portfolio/:splat"
  status = 200
[[redirects]]
  from = "/impressum/*"
  to = "/impressum/:splat"
  status = 200